# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-29 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('views', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[(b'SEO', b'SEO'), (b'SEM', b'SEM'), (b'Social Media', b'Social Media')], max_length=30, null=True)),
                ('type', models.CharField(choices=[(b'Bug', b'Bug'), (b'Feature Request', b'Feature Request')], max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'img')),
                ('upvotes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[(b'To Do', b'To Do'), (b'Doing', b'Doing'), (b'Done', b'Done')], default=b'To Do', max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
